### ISSUE TITLE
Manifest link needs to be to raw

### ISSUE THREAD

**Issue by thoth-process** [draconas1/foundry-4e-tools#1]
The manifest link is currently https://github.com/draconas1/foundry-4e-tools/blob/main/module.json which will not work.  It needs to be https://raw.githubusercontent.com/draconas1/foundry-4e-tools/main/module.json in both the README and in the module.json instead.

**Comment by draconas1** [comment]
Ooops, many thanks.  This has been fixed in 0.0.2
