### ISSUE TITLE
[Request] More "utility" functions for Token Action HUD

### ISSUE THREAD

**Issue by FoxLee** [draconas1/foundry-4e-tools#13]
Any chance we could get a few more functions for Token Action HUD?

I would find it useful for the Utility category to contain the other "clickable" effects on the character sheet: Second Wind, Short Rest and Extended Rest, and Action Point. (And I suppose Death Save would be useful too, not that it ever comes up in my group.)

(I'm working on the assumption that this module decides what appears there for 4e, rather than it being determined by Token Action HUD. Please excuse me if that's not the case!)

**Comment by draconas1** [comment]
I will look into some of them in the future, unlikely to be the Rests though as they are non combat things which people can open their character sheet for.

**Comment by draconas1** [comment]
I have added some additional hooks to 4E, once they are in I will write the TAH section to work with them.

**Comment by draconas1** [comment]
https://github.com/Drental/fvtt-tokenactionhud/pull/184 will add these to TAH

**Comment by draconas1** [comment]
These should be available with release 2.2.7 of TAH and 0.2.70 of DnD4E
