### ISSUE TITLE
Auto Roll Power macro only Auto rolling the attack roll, not the damage. 

### ISSUE THREAD

**Issue by NuptupTDOW** [draconas1/foundry-4e-tools#15]
So, I was messing around with planning to use the auto roll attack and damage to expedite my combats and I was inserting the macro into my powers and it is only auto rolling the attack roll and not the damage or any healing associated to the power. 

I was thinking it might be checking for a "Probable Hit" but even when targeting and hitting, it doesn't trigger the damage, so I am assuming it's not related to that (Though, it would be really cool if it could detect a hit and only roll the damage upon connection.)

So, anyway, I was just wondering if you could take another pass at this?

**Comment by draconas1** [comment]
No it's crashing.  That's exciting, didn't used to do that.

If you open your console window (F12) and run it you will probably see  something like

```
Uncaught (in promise) Error: Roll.safeEval produced a non-numeric result from expression ""
[Detected 1 package: system:dnd4e]
    at Function.safeEval (foundry.js:6938)
    at RollWithOriginalExpression._evaluateTotal (foundry.js:6864)
    at RollWithOriginalExpression._evaluate (foundry.js:6815)
    at RollWithOriginalExpression.evaluate (foundry.js:6778)
    at RollWithOriginalExpression.toMessage (foundry.js:7425)
    at performDamageRollAndCreateChatMessage (dice.js:421)
    at damageRoll (dice.js:304)
    at Item4e.rollDamage (entity.js:1171)
    at async eval (eval at _executeScript (foundry.js:17014), <anonymous>:18:5)
```

**Comment by draconas1** [comment]
Ok I have found the problem - in the latest version of the system a fix was added around dealing with bonuses, that fix breaks all Fast-Forwarded damage rolls.  

I will raise a bug on the system, I am away this weekend so can't look at it.  In the meantime, if you edit the macro to not pass the event in to damage and healing you will get the roll dialogs for them and they should work.

**Comment by NuptupTDOW** [comment]
So, just to confirm I understand what you're saying. If I remove the last two if statements that deal with damage and healing, it will automatically roll the attack, and then it will automatically pop up the text box for damage where I enter variables that might be applicable, meaning I don't need to click on the damage button? If that's the case, it's at least kind of convenient so if a attack misses I don't have to do it and I can just cancel out that box. But I just want to make sure I understand that correctly before I make the assumption and go with that.

**Comment by draconas1** [comment]
Edit the last 2 statements to remove the `event` that is passed into rollDamage or rollHealing and then yes, you will get the popup as you describe.

**Comment by NuptupTDOW** [comment]
Oh ok, gotcha
