### ISSUE TITLE
Macro Help: Healing/Temp HP macro

### ISSUE THREAD

**Issue by BasiliskOnline** [draconas1/foundry-4e-tools#17]
Hi! Thanks so much for these tools, i've been bust setting up a lot of automation for my game while i build out powers.

I was using your Temp HP/Healing macro to set up a temp HP automation on the end of recuperating strike and I ran into an issue, being mostly clueless about this stuff, and hope you can help if you find a minute!
```
const hpValue = @conMod;
await this.actor.applyTempHpChange(hpValue);

ChatMessage.create({
 user: game.user._id,
 speaker: ChatMessage.getSpeaker({token: this.actor}),
 content: `Gained ${hpValue} Temp HP`
});
```
However change "5" from your original macro (const hpValue) to @conMod didn't work, how can I set it up to reference the con modifier?

Also I will need to also do one for a Con modifier + 5, if I'll need something different than just adding +5 to the above.

Thanks again! <3

**Comment by draconas1** [comment]
So @conmod won't work in a macro you need to reference the attribute mod
directly in the actor. I can't look it up right now, best bet fir finding
it is either using the console to explore an actor or asking on the dnd 4e
discord.
It's something like actor.data.attributes.con.mod

**Comment by draconas1** [comment]
`const hpValue = 5 + this.actor.system.abilities.con.mod;`
