### ISSUE TITLE
[Suggestion] Allow auto bloodied to use the small icon

### ISSUE THREAD

**Issue by Marcloure** [draconas1/foundry-4e-tools#19]
Currently, the only option we have when turning on "Auto Bloodied" is the large bloodied icon, which covers the token art. It would be nice to have an option to use the small icon istead.

I have changed the "overlay" property set on line 104 of `auto-bloodied-dead.js` on my end as a quick fix. I changed it to: `"overlay": statusToCheck === dead`, so dead will still use the large icon.

**Comment by draconas1** [comment]
Sure, I can look at that as a config option for me to release.

**Comment by draconas1** [comment]
This should now be available as a setting in 3.0.3 release.  Look for it directly under the auto bloodied option.
