### ISSUE TITLE
Change Dead Status Icon Not Applying

### ISSUE THREAD

**Issue by NightB1ade** [draconas1/foundry-4e-tools#29]
# Issue
As the title suggests the setting to change the dead status icon to your red skull/bones one does not seem to be applying.  I think it was working prior to the last upgrade and has only just changed based on the latest update.

Just made a completely clean table in with the D&D4e system and only this module activated and issue still occurs.
![image](https://github.com/user-attachments/assets/3a10fc41-84c4-4559-b446-7bf5bdf9425b)

Please let me know what other tests I can do to aid in anything.

# Software Versions
- Foundry v12.331
- D&D4e v0.5.11
- Drac's Foundry 4e Tools v5.0.3

**Comment by draconas1** [comment]
Exciting, I'll try to have a look, this was working for me last week when I
ran a game.

Obvious question is do you have anything relevant in your error log (most
relevant will probably be on start, as it switches the icon when you load
into the world)

**Comment by NightB1ade** [comment]
Nothing in my error log that looks relevant (today's at least).

Is the easiest way to get the old version of the module back to test with downloading it from the releases page and manually replacing it?  Can do a test with that if that helps.

**Comment by draconas1** [comment]
Shouldn't make any difference.  It's not a piece of code I've edited
recently.

**Comment by draconas1** [comment]
I've been trying to replicate this but can't, I've tried turning it on, turning it off, all fine.  

It did show a bug where I literally nuke the dead-state icon if you have Drac's tools installed but have "new dead icon" unchecked, then you get no icons.    There is a new version released to fix that.

Important note: it's not retroactive.  Once a status has been applied it as that icon for the rest of its life, my setting will only effect newly applied conditions.

**Comment by NightB1ade** [comment]
Hmm, well was definitely doing tests removing/adding it (and just tested again).  So it must be an issue of my install then...  I'll try some more variants clearing it all down etc. to try to get it to work and feed back if I'm successful.

Though I'm on a flight tomorrow so may be later in the weekend/earlier next week when I get around to it.

Thanks for your time and causing you trouble so far already!

**Comment by NightB1ade** [comment]
As a very quick test before I head to sleep, I copied out my Foundry folder and then deleted everything in that folder to start afresh with the configuration side of things.

- Installed 4e system
- Installed your tools
- Created new world
- Went in
- Activated module
- Activated setting
- Completely closed down Foundry
- Rebooted

Still the same!  At this rate - I might try reinstalling the whole of Foundry next :P

**Comment by NightB1ade** [comment]
Oh...  I'm an absolute idiot...  I hadn't realised I was testing on a PC character as opposed to an NPC character...  And I was confusing the _dying_ icon with the _dead_ icon (cos was testing by setting to 0 HP)...

Sooooooo sorry!

**Comment by draconas1** [comment]
Ahhh yes, and the damn thing is indistinct enough that I didn't spot it on
your screenshot that it was dying not dead.

I might look at a new dying icon as well.

**Comment by NightB1ade** [comment]
Well serves me right for doing testing using the mysterious man icon too.  That teaches me to actually check what icon is appearing next time.  Though if you're going for a new dying icon too - I'd definitely appreciate that for me not making a fool of myself again! Doh!
